# Generated by Django 3.1.2 on 2020-12-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201208_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=50)),
                ('born', models.DateField(blank=True, null=True)),
                ('instrument', models.CharField(choices=[('LEAD_GUITAR', 'lead guitar'), ('RHYTHM_GUITAR', 'rhythm guitar'), ('BASS', 'bass'), ('DRUMS', 'drums'), ('VOCALS', 'vocals')], default='unknown', max_length=30, verbose_name='Primary instrument')),
                ('alive', models.BooleanField(choices=[('ALIVE', 'alive'), ('DECEASED', 'deceased')], default='ALIVE', verbose_name='Alive/Deceased')),
                ('quote', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.band')),
            ],
        ),
    ]
