# Generated by Django 3.1.2 on 2020-12-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20201212_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='alive',
            field=models.BooleanField(choices=[(True, 'alive'), (False, 'deceased')], default='alive', verbose_name='Alive/Deceased'),
        ),
    ]
