# Generated by Django 3.1.2 on 2020-12-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20201212_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(choices=[('lead guitar', 'lead guitar'), ('rhythm guitar', 'rhythm guitar'), ('bass', 'bass'), ('drums', 'drums'), ('vocals', 'vocals')], default='unknown', max_length=30, verbose_name='Primary instrument'),
        ),
    ]
